/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cafeteria;

import GestionDatos.DB_Usuario;
import clases.Usuario;
import clases.ValidacionDatos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 1 - Proyecto Cafeteria - Curso 6-2
 */
public class AgregarFrame_Usuario extends javax.swing.JFrame {

    private Usuario usuario;
    private DB_Usuario db_user;
    /**
     * Creates new form AgregarFrame_Usuario
     */
    public AgregarFrame_Usuario() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(249, 248, 204));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new java.awt.TextField();
        txtApellidosUsuario = new java.awt.TextField();
        txtUsuario = new java.awt.TextField();
        txtContraseñaUsuario = new java.awt.TextField();
        txtCedulaUsuario = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreoUsuario = new java.awt.TextField();
        txtTelefonoUsuario = new java.awt.TextField();
        jLabel10 = new javax.swing.JLabel();
        txtRolUsuario = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Usuarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarUsuario.setBackground(new java.awt.Color(204, 250, 250));
        btnRegistrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarUsuario.setText("Registrar");
        btnRegistrarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 70, 30));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel6.setText("Nombre de usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel2.setText("Cédula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));
        jPanel1.add(txtApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));
        jPanel1.add(txtContraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));
        jPanel1.add(txtCedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 180, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel8.setText("Correo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel9.setText("Teléfono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        jPanel1.add(txtCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, -1));
        jPanel1.add(txtTelefonoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 180, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel10.setText("Rol:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));
        jPanel1.add(txtRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconoCliente.png"))); // NOI18N
        jLabel1.setText("Agregar Usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setIconTextGap(15);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Comprueba que los campos esten llenos
    private boolean isNullorEmpty(String text){
        return text == null || text.isEmpty();
    }
     
    private void limpiarCampos(){
        txtApellidosUsuario.setText("");
        txtCedulaUsuario.setText("");
        txtContraseñaUsuario.setText("");
        txtCorreoUsuario.setText("");
        txtNombreUsuario.setText("");
        txtRolUsuario.setText("");
        txtTelefonoUsuario.setText("");
        txtUsuario.setText("");
    }
     
    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        usuario = new Usuario();
        db_user = new DB_Usuario();
        
        boolean camposLlenos = !isNullorEmpty(txtApellidosUsuario.getText()) && !isNullorEmpty(txtCedulaUsuario.getText()) &&
                !isNullorEmpty(txtContraseñaUsuario.getText()) && !isNullorEmpty(txtCorreoUsuario.getText()) &&
                !isNullorEmpty(txtNombreUsuario.getText()) && !isNullorEmpty(txtRolUsuario.getText()) &&
                !isNullorEmpty(txtTelefonoUsuario.getText()) && !isNullorEmpty(txtUsuario.getText());
        
        boolean camposValidacion = isNullorEmpty(ValidacionDatos.cedula(txtCedulaUsuario.getText())) && 
                isNullorEmpty(ValidacionDatos.correo(txtCorreoUsuario.getText())) && 
                isNullorEmpty(ValidacionDatos.telefono(txtTelefonoUsuario.getText())) && 
                isNullorEmpty(ValidacionDatos.texto(txtApellidosUsuario.getText())) && 
                isNullorEmpty(ValidacionDatos.texto(txtRolUsuario.getText())) && 
                isNullorEmpty(ValidacionDatos.texto(txtNombreUsuario.getText()));
        
        usuario.setNombre(txtNombreUsuario.getText());
        usuario.setApellido(txtApellidosUsuario.getText());
        usuario.setUsuario_ingreso(txtUsuario.getText());
        usuario.setContrasenia(txtContraseñaUsuario.getText());
        usuario.setCorreo(txtCorreoUsuario.getText());
        usuario.setTelefono(txtTelefonoUsuario.getText());
        usuario.setCedula(txtCedulaUsuario.getText());
        usuario.setRol(txtRolUsuario.getText());
        
        if(camposLlenos){
            if(camposValidacion){
                db_user.guardarUsuario(usuario);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "SE DETECTO CAMPOS CON INFORMACION INVALIDA");
            }
        }else{
            JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
        }
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtApellidosUsuario;
    private java.awt.TextField txtCedulaUsuario;
    private java.awt.TextField txtContraseñaUsuario;
    private java.awt.TextField txtCorreoUsuario;
    private java.awt.TextField txtNombreUsuario;
    private java.awt.TextField txtRolUsuario;
    private java.awt.TextField txtTelefonoUsuario;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
