/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cafeteria;

import GestionDatos.DB_Pedido;
import clases.Detalle_Pedido;
import clases.Pedido;
import clases.ValidacionDatos;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Grupo 1 - Proyecto Cafeteria - Curso 6-2
 */
public class AgregarFrame_Pedidos extends javax.swing.JFrame {

    private DB_Pedido db_pedido;
    private Pedido pedido;
    private Detalle_Pedido detalle;
    private DefaultTableModel modelo;
    private int numero;
    
    /**
     * Creates new form AgregarFrame_Pedidos
     */
    public AgregarFrame_Pedidos() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(249, 248, 204));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        llenarComboBox();
        columnasTable();
        numeroAutomatico();  
    }
    
    private void columnasTable(){
        modelo = new DefaultTableModel();
        modelo.addColumn("NRO");
        modelo.addColumn("MENU");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("SUBTOTAL");
        tablePedidos.setModel(modelo);
    }
    
    private void llenarComboBox(){
        db_pedido = new DB_Pedido();
        db_pedido.consultaMenus(cmbMenu);
        cmbMenu.setSelectedIndex(-1);
    }
    
    private void numeroAutomatico(){
        db_pedido = new DB_Pedido();
        numero = db_pedido.consultaUltimoNroPedido(numero);
        //System.out.println(numero);
        numero = numero+1;
        //System.out.println(numero);
        String numeroText = String.valueOf(numero);
        lblNro.setText(numeroText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCantidad = new java.awt.TextField();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new java.awt.TextField();
        lblNro = new javax.swing.JLabel();
        btnFijar = new javax.swing.JButton();
        cmbMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        btnGuardarPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEDIDOS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregarIcon.png"))); // NOI18N
        btnAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 40, 40));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel4.setText("Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("NRO DE PEDIDO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 180, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel2.setText("Menu:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel8.setText("Cantidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 50, -1));

        lblNro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNro.setText("_________");
        jPanel1.add(lblNro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 30));

        btnFijar.setBackground(new java.awt.Color(204, 250, 250));
        btnFijar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFijar.setText("Fijar");
        btnFijar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnFijar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFijar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 20));

        jPanel1.add(cmbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 20));

        tablePedidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePedidos);

        btnGuardarPedido.setBackground(new java.awt.Color(204, 250, 250));
        btnGuardarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardarPedido.setText("Finalizar Pedido");
        btnGuardarPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPedidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("SUBTOTAL:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("IVA:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 2, 48)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconoFactura.png"))); // NOI18N
        jLabel9.setText("PEDIDO");
        jLabel9.setIconTextGap(20);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSubtotal.setText("0.0");

        lblIva.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIva.setText("0.0");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardarPedido)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarPedido)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNullorEmpty(String text){
        return text == null || text.isEmpty();
    }
    
    private void limpiarCampos(){
        txtCantidad.setText("");
        txtPrecio.setText("");
        cmbMenu.setSelectedIndex(0);
    }
    
    private void setSubtotal(){
        double subTotal;
        int cantidad;
        double precio;
        
        subTotal = Double.parseDouble(lblSubtotal.getText());
        precio = Double.parseDouble(txtPrecio.getText());
        cantidad = Integer.parseInt(txtCantidad.getText());
        subTotal = subTotal + (precio*cantidad);
        subTotal = Math.round(subTotal*100.0)/100.0;
        
        lblSubtotal.setText(String.valueOf(subTotal));
    }
    
    private void setIva(){
        double iva;
        double subtotal;
        
        subtotal = Double.parseDouble(lblSubtotal.getText());
        iva = subtotal*0.15;
        System.out.println(iva);
        iva = Math.round(iva*100.0)/100.0;
        System.out.println(iva);

        
        lblIva.setText(String.valueOf(iva));    
    }
    
    private void setTotal(){
        double total;
        double subtotal;
        double iva;
        
        subtotal = Double.parseDouble(lblSubtotal.getText());
        iva = Double.parseDouble(lblIva.getText());
        total = subtotal + iva;
        total = Math.round(total*100.0)/100.0;
        
        lblTotal.setText(String.valueOf(total));
    }
    
    private void addDetalles(){
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double precio = Double.parseDouble(txtPrecio.getText());
        double subtotal = cantidad*precio;
        
        modelo = (DefaultTableModel) tablePedidos.getModel();
        
        Object [] datos = new Object [5];
        datos[0]=lblNro.getText();
        datos[1]=cmbMenu.getSelectedItem().toString();
        datos[2]=txtPrecio.getText();
        datos[3]=txtCantidad.getText();
        datos[4]=subtotal;
        modelo.addRow(datos);
    }
    
    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
        db_pedido = new DB_Pedido();
        pedido = new Pedido();
        boolean campoLleno=!isNullorEmpty(txtCliente.getText());
        boolean campoValido=isNullorEmpty(ValidacionDatos.texto(txtCliente.getText()));
        
        if(campoLleno){
            if(campoValido){
                pedido.setNumero_pedido(Integer.parseInt(lblNro.getText()));
                pedido.setCliente(txtCliente.getText());
                pedido.setTotal(Double.parseDouble(lblTotal.getText()));
                db_pedido.guardarPedido(pedido);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"SE DETECTO CARACTERES INVALIDOS");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el nombre del cliente");
        }
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        db_pedido = new DB_Pedido();
        detalle = new Detalle_Pedido();
        boolean camposLlenos = !isNullorEmpty(txtPrecio.getText()) && !isNullorEmpty(txtCantidad.getText()) &&
                !isNullorEmpty(txtCliente.getText());
        
        if(camposLlenos){
            detalle.setNumero_pedido(Integer.parseInt(lblNro.getText()));
            detalle.setMenu(cmbMenu.getSelectedItem().toString());
            detalle.setPrecio(Double.parseDouble(txtPrecio.getText()));
            detalle.setCantidad(Integer.parseInt(txtCantidad.getText()));
            detalle.setSubTotal((detalle.getPrecio())*detalle.getCantidad());
            
            db_pedido.guardarDetallePedido(detalle);
            
            addDetalles();
            setSubtotal();
            setIva();
            setTotal();
            limpiarCampos();
            
        }else{
            JOptionPane.showMessageDialog(null,"FALTAN CAMPOS DE LLENAR");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnFijarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijarActionPerformed
        txtCliente.setEditable(false);
        txtCliente.setEnabled(false);
    }//GEN-LAST:event_btnFijarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFijar;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablePedidos;
    private java.awt.TextField txtCantidad;
    private java.awt.TextField txtCliente;
    private java.awt.TextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
