/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cafeteria;

import GestionDatos.DB_Reservas;
import clases.Reservas;
import clases.ValidacionDatos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 1 - Proyecto Cafeteria - Curso 6-2
 */
public class AgregarFrame_Reservas extends javax.swing.JFrame {

    private DB_Reservas db_reservas;
    private Reservas reserva;
    
    /**
     * Creates new form AgregarFrame_Reservas
     */
    public AgregarFrame_Reservas() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(249, 248, 204));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtNumero = new java.awt.TextField();
        txtTelefono = new java.awt.TextField();
        txtNumeroPersonas = new java.awt.TextField();
        txtDia = new java.awt.TextField();
        txtAño = new java.awt.TextField();
        txtMes = new java.awt.TextField();
        txtNombreCliente = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Reserva");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventarioIcon.png"))); // NOI18N
        jLabel8.setText("RESERVA");

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel2.setText("Nombre del cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 132, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 16)); // NOI18N
        jLabel1.setText("Numero de Reserva:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel6.setText("Numero de personas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel4.setText("Año:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel5.setText("Mes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 15)); // NOI18N
        jLabel7.setText("Dia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconoGuardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 90, 120, -1));
        jPanel1.add(txtNumeroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 30, -1));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, -1));
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 40, -1));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, -1));
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNullorEmpty(String text){
        return text == null || text.isEmpty();
    }
    
    private void limpiarCampos(){
        txtAño.setText("");
        txtDia.setText("");
        txtMes.setText("");
        txtNombreCliente.setText("");
        txtNumero.setText("");
        txtNumeroPersonas.setText("");
        txtTelefono.setText("");
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        db_reservas = new DB_Reservas();
        reserva = new Reservas();
        
        boolean camposLlenos = !isNullorEmpty(txtAño.getText()) && !isNullorEmpty(txtDia.getText()) && !isNullorEmpty(txtMes.getText()) &&
                !isNullorEmpty(txtNombreCliente.getText()) && !isNullorEmpty(txtNumero.getText()) && !isNullorEmpty(txtNumeroPersonas.getText()) &&
                !isNullorEmpty(txtTelefono.getText());
        boolean camposValidos = isNullorEmpty(ValidacionDatos.texto(txtNombreCliente.getText())) && 
                isNullorEmpty(ValidacionDatos.telefono(txtTelefono.getText()));
        
        if(camposLlenos){
            if(camposValidos){
                reserva.setAnio(Integer.parseInt(txtAño.getText()));
                reserva.setCantidad(Integer.parseInt(txtNumeroPersonas.getText()));
                reserva.setCliente(txtNombreCliente.getText());
                reserva.setDia(Integer.parseInt(txtDia.getText()));
                reserva.setMes(Integer.parseInt(txtMes.getText()));
                reserva.setNumero(Integer.parseInt(txtNumero.getText()));
                reserva.setTelefono(txtTelefono.getText());
                
                db_reservas.guardarReserva(reserva);
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "SE DETECTO INFORMACION NO VALIDA EN LOS CAMPOS");
            }   
        }else{
            JOptionPane.showMessageDialog(null, "LLENE TODO LOS CAMPOS");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtAño;
    private java.awt.TextField txtDia;
    private java.awt.TextField txtMes;
    private java.awt.TextField txtNombreCliente;
    private java.awt.TextField txtNumero;
    private java.awt.TextField txtNumeroPersonas;
    private java.awt.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
